[package]
name = "cch23-snowman222"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
anyhow = "1.0.79"
serde = { version = "1.0.196", features = ["derive"] }
shuttle-actix-web = "0.38.0"
shuttle-runtime = "0.38.0"
tokio = "1.36.0"
tracing = "0.1.40"
